name = "secret-box"
main = "src/index.ts"
account_id = ""
workers_dev = true
compatibility_date = "2022-04-14"

kv_namespaces = [
	{ binding = "CREDENTIALS", preview_id = "08f012b41df44fd3b6849100d02b7cba", id = "08f012b41df44fd3b6849100d02b7cba" }
]

node_compat = true

[miniflare]
env_path=".env"
