import { Secp256k1, Secp256k1Signature, sha256 } from "@cosmjs/crypto";

/**
 * Verify that a signature is valid
 *
 * @param signature signature (as generated by the generateSignature function)
 * @param signedBytes signed bytes (as generated by the generateSignDocBytes function or by the signMessage function)
 * @param publicKey public key of the signing key pair (secp256k1)
 */
export const verifySignature = async (
  signature: Uint8Array,
  signedBytes: Uint8Array,
  publicKey: Uint8Array
): Promise<boolean> => {
  const valid = await Secp256k1.verifySignature(
    Secp256k1Signature.fromFixedLength(signature),
    sha256(signedBytes),
    publicKey
  );
  return valid;
};
